name: course_learning_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  shared_preferences: ^2.5.5
  video_player: ^2.11.1
  chewie: ^1.14.0
  firebase_core: ^3.15.2
  cloud_firestore: ^5.6.2
  firebase_auth: ^5.4.1
  firebase_storage: ^12.4.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  # أضف assets هنا
  assets:
    - assets/icon/

# أضف التكوين ده في النهاية
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"