// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_on_widgets
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkQ6Cqwpnwt8OfQ1T_jsW3rRVEc7_BnLw',
    appId: '1:456395953392:web:632d3c70a31cff7fa69e35',
    messagingSenderId: '456395953392',
    projectId: 'course-learning-app-b4be1',
    authDomain: 'course-learning-app-b4be1.firebaseapp.com',
    storageBucket: 'course-learning-app-b4be1.firebasestorage.app',
    measurementId: 'G-4XEPC035C1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAD82RjuvJf5E72MLLCNLDSOCV-drxUWsw',
    appId: '1:456395953392:android:6b6e7ef5f54de613a69e35',
    messagingSenderId: '456395953392',
    projectId: 'course-learning-app-b4be1',
    storageBucket: 'course-learning-app-b4be1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0MxbKaQRGP8mboTd-7cMJZmArUpH2I_U',
    appId: '1:456395953392:ios:2d1158199e1c5d51a69e35',
    messagingSenderId: '456395953392',
    projectId: 'course-learning-app-b4be1',
    storageBucket: 'course-learning-app-b4be1.firebasestorage.app',
    iosClientId: '456395953392-4jn8kemispk6vt6j0vbg22tkq7gvk5pj.apps.googleusercontent.com',
    iosBundleId: 'com.example.courseLearningApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0MxbKaQRGP8mboTd-7cMJZmArUpH2I_U',
    appId: '1:456395953392:ios:2d1158199e1c5d51a69e35',
    messagingSenderId: '456395953392',
    projectId: 'course-learning-app-b4be1',
    storageBucket: 'course-learning-app-b4be1.firebasestorage.app',
    iosClientId: '456395953392-4jn8kemispk6vt6j0vbg22tkq7gvk5pj.apps.googleusercontent.com',
    iosBundleId: 'com.example.courseLearningApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkQ6Cqwpnwt8OfQ1T_jsW3rRVEc7_BnLw',
    appId: '1:456395953392:web:c70862b6fe14d9f7a69e35',
    messagingSenderId: '456395953392',
    projectId: 'course-learning-app-b4be1',
    authDomain: 'course-learning-app-b4be1.firebaseapp.com',
    storageBucket: 'course-learning-app-b4be1.firebasestorage.app',
    measurementId: 'G-MS7546H6F7',
  );

}