// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_on_widgets
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyBkQ6Cqwpnwt8OfQ1T_jsW3rRVEc7_BnLw",
    authDomain: "course-learning-app-b4be1.firebaseapp.com",
    projectId: "course-learning-app-b4be1",
    storageBucket: "course-learning-app-b4be1.firebasestorage.app",
    messagingSenderId: "456395953392",
    appId: "1:456395953392:web:632d3c70a31cff7fa69e35",
    measurementId: "G-4XEPC035C1",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyBkQ6Cqwpnwt8OfQ1T_jsW3rRVEc7_BnLw",
    appId: "1:456395953392:android:632d3c70a31cff7fa69e35",
    messagingSenderId: "456395953392",
    projectId: "course-learning-app-b4be1",
    storageBucket: "course-learning-app-b4be1.firebasestorage.app",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyBkQ6Cqwpnwt8OfQ1T_jsW3rRVEc7_BnLw",
    appId: "1:456395953392:ios:632d3c70a31cff7fa69e35",
    messagingSenderId: "456395953392",
    projectId: "course-learning-app-b4be1",
    storageBucket: "course-learning-app-b4be1.firebasestorage.app",
    iosBundleId: "com.example.courseLearningApp",
  );
}
